### ISSUE TITLE
Illegal item system does not work [API 6]

### ISSUE THREAD

**Issue by crymates** [dchaosknight/FriskStick-Sponge#1]
If I wait the 5 secs for frisking player, it works with legal items.
But if u have illegal items it does not say anything and do not auto jail the player.

**Comment by dchaosknight** [comment]
Does anything appear in the console? What server version are you using?

**Comment by crymates** [comment]
Ya hold 2 minutes, brb.

**Comment by crymates** [comment]
There we go:

`[23:45:03] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task friskstick-S-4 owned by Plugin{id=friskstick, name=FriskStick, version=1.0.0, description=A plugin to frisk players!, authors=[dchaosknight], source=/home/servers/sponge_mc/mods/FriskStick-v1.0.1.jar}, but an error occured.
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[minecraft_server.1.11.jar:?]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[minecraft_server.1.11.jar:?]
	at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513) ~[aaw.class:?]
	at org.spongepowered.common.item.inventory.lens.impl.fabric.DefaultInventoryFabric.setStack(DefaultInventoryFabric.java:61) ~[DefaultInventoryFabric.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter.poll(SlotAdapter.java:104) ~[SlotAdapter.class:1.11-2178-6.0.0-BETA-1966]
	at io.github.dchaosknight.friskstick.util.FriskUtil.lambda$friskPlayer$0(FriskUtil.java:63) ~[FriskUtil.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_102]
	at io.github.dchaosknight.friskstick.util.FriskUtil.friskPlayer(FriskUtil.java:36) ~[FriskUtil.class:?]
	at io.github.dchaosknight.friskstick.listeners.FriskListener.lambda$onFriskRequest$8(FriskListener.java:162) ~[FriskListener.class:?]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.11-2178-6.0.0-BETA-1966]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_102]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.11-2178-6.0.0-BETA-1966]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:238) [SpongeMod.class:1.11-2178-6.0.0-BETA-1966]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:275) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[23:45:05] [Server thread/DEBUG] [mixin/]: Mixing common.MixinSpongeProxyBlockAccess from mixins.forge.core.json into org.spongepowered.common.world.SpongeProxyBlockAccess
`

In this example it's about an Diamond Sword.
Nothing happens ingame when checking for illegal stuff.

**Comment by crymates** [comment]
Using spongeforge-1.11-2178-6.0.0-BETA-1966 ;)

**Comment by dchaosknight** [comment]
I just did some testing on this and found that it works for later updates of SpongeForge (I used spongeforge-1.11-2178-6.0.0-BETA-1999). My best guess for what was happening based off the error you posted is that the inventory system wasn't fully functioning in the version you have. If you update your server, this issue should go away.

**Comment by crymates** [comment]
Well, really thx alot! ;)

**Comment by yololetsplay** [comment]
Well I found another bug:

If auto-jailing is enabled and u search for illegal items and the player is on the run, U get instant jailed also if you are on run.
If u disable auto-jailing, the "on the run" function does not work.

Greetz,
Hannes
